-- Persist product Power Dialer outcomes/events without overloading call_queue.status.
--
-- Safe to run more than once against the shared Supabase project.

create table if not exists call_queue_events (
  id                bigint generated by default as identity primary key,
  organization_id   integer references organizations(id) on delete cascade,
  call_queue_id     bigint references call_queue(id) on delete cascade,
  contact_id        integer references contacts(id) on delete set null,
  actor_user_id     uuid references users(id) on delete set null,
  event_type        text not null,
  outcome           text,
  ui_status         text,
  db_status         text,
  duration_seconds  integer,
  voicemail_title   text,
  payload           jsonb not null default '{}'::jsonb,
  created_at        timestamp with time zone not null default now()
);

create index if not exists call_queue_events_organization_created_idx
  on call_queue_events(organization_id, created_at desc);

create index if not exists call_queue_events_call_queue_created_idx
  on call_queue_events(call_queue_id, created_at desc);

create index if not exists call_queue_events_contact_created_idx
  on call_queue_events(contact_id, created_at desc);

grant all on call_queue_events to service_role;
grant select on call_queue_events to authenticated;
